items:
- uid: com.microsoft.azure._cloud_exception
  id: _cloud_exception
  parent: com.microsoft.azure
  children:
  - com.microsoft.azure._cloud_exception.CloudException()
  - com.microsoft.azure._cloud_exception.CloudException(final String)
  - com.microsoft.azure._cloud_exception.CloudException(final String,final Throwable)
  - com.microsoft.azure._cloud_exception.CloudException(final Throwable)
  - com.microsoft.azure._cloud_exception.getBody()
  - com.microsoft.azure._cloud_exception.getResponse()
  - com.microsoft.azure._cloud_exception.setBody(CloudError)
  - com.microsoft.azure._cloud_exception.setResponse(Response)
  - com.microsoft.azure._cloud_exception.toString()
  href: com.microsoft.azure._cloud_exception.yml
  langs:
  - java
  name: CloudException
  fullName: com.microsoft.azure.CloudException
  type: Class
  source:
    remote: &o0
      path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/CloudException.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/CloudException.java
    startLine: 15
  package: com.microsoft.azure
  summary: <p>Exception thrown for an invalid response with custom error information. </p>
  syntax:
    content: public class CloudException extends RestException
  inheritance:
  - java.lang.Object
  - Exception
  - com.microsoft.rest._rest_exception
  inheritedMembers:
  - com.microsoft.rest._rest_exception.RestException()
  - com.microsoft.rest._rest_exception.RestException(String)
  - com.microsoft.rest._rest_exception.RestException(Throwable)
  - com.microsoft.rest._rest_exception.RestException(String,Throwable)
- uid: com.microsoft.azure._cloud_exception.CloudException()
  id: CloudException()
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  langs:
  - java
  name: CloudException()
  fullName: com.microsoft.azure.CloudException.CloudException()
  type: Constructor
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/CloudException.java
    startLine: 29
  package: com.microsoft.azure
  summary: <p>Initializes a new instance of the ServiceException class. </p>
  syntax:
    content: public CloudException()
- uid: com.microsoft.azure._cloud_exception.CloudException(final String)
  id: CloudException(final String)
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  langs:
  - java
  name: CloudException(final String message)
  fullName: com.microsoft.azure.CloudException.CloudException(final String message)
  type: Constructor
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/CloudException.java
    startLine: 36
  package: com.microsoft.azure
  summary: >-
    <p>Initializes a new instance of the ServiceException class.</p>

    <p></p>
  syntax:
    content: public CloudException(final String message)
    parameters:
    - id: message
      type: 3d93591e
      description: <p>The exception message. </p>
- uid: com.microsoft.azure._cloud_exception.CloudException(final String,final Throwable)
  id: CloudException(final String,final Throwable)
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  langs:
  - java
  name: CloudException(final String message, final Throwable cause)
  fullName: com.microsoft.azure.CloudException.CloudException(final String message, final Throwable cause)
  type: Constructor
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/CloudException.java
    startLine: 46
  package: com.microsoft.azure
  summary: >-
    <p>Initializes a new instance of the ServiceException class.</p>

    <p></p>
  syntax:
    content: public CloudException(final String message, final Throwable cause)
    parameters:
    - id: message
      type: 3d93591e
      description: <p>the exception message </p>
    - id: cause
      type: fa00b19f
      description: <p>exception that caused this exception to occur </p>
- uid: com.microsoft.azure._cloud_exception.CloudException(final Throwable)
  id: CloudException(final Throwable)
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  langs:
  - java
  name: CloudException(final Throwable cause)
  fullName: com.microsoft.azure.CloudException.CloudException(final Throwable cause)
  type: Constructor
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/CloudException.java
    startLine: 55
  package: com.microsoft.azure
  summary: >-
    <p>Initializes a new instance of the ServiceException class.</p>

    <p></p>
  syntax:
    content: public CloudException(final Throwable cause)
    parameters:
    - id: cause
      type: fa00b19f
      description: <p>exception that caused this exception to occur </p>
- uid: com.microsoft.azure._cloud_exception.getBody()
  id: getBody()
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  langs:
  - java
  name: getBody()
  fullName: CloudError com.microsoft.azure.CloudException.getBody()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/CloudException.java
    startLine: 73
  package: com.microsoft.azure
  summary: >-
    <p>Gets the HTTP response body.</p>

    <p></p>
  syntax:
    content: public CloudError getBody()
    return:
      type: com.microsoft.azure._cloud_error
      description: <p>the response body </p>
- uid: com.microsoft.azure._cloud_exception.getResponse()
  id: getResponse()
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  langs:
  - java
  name: getResponse()
  fullName: Response com.microsoft.azure.CloudException.getResponse()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/CloudException.java
    startLine: 64
  package: com.microsoft.azure
  summary: >-
    <p>Gets information about the associated HTTP response.</p>

    <p></p>
  syntax:
    content: public Response getResponse()
    return:
      type: e9d34ed6
      description: <p>the HTTP response </p>
- uid: com.microsoft.azure._cloud_exception.setBody(CloudError)
  id: setBody(CloudError)
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  langs:
  - java
  name: setBody(CloudError body)
  fullName: void com.microsoft.azure.CloudException.setBody(CloudError body)
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/CloudException.java
    startLine: 91
  package: com.microsoft.azure
  summary: >-
    <p>Sets the HTTP response body.</p>

    <p></p>
  syntax:
    content: public void setBody(CloudError body)
    parameters:
    - id: body
      type: com.microsoft.azure._cloud_error
      description: <p>the response object </p>
- uid: com.microsoft.azure._cloud_exception.setResponse(Response)
  id: setResponse(Response)
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  langs:
  - java
  name: setResponse(Response response)
  fullName: void com.microsoft.azure.CloudException.setResponse(Response response)
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/CloudException.java
    startLine: 82
  package: com.microsoft.azure
  summary: >-
    <p>Sets the HTTP response.</p>

    <p></p>
  syntax:
    content: public void setResponse(Response response)
    parameters:
    - id: response
      type: e9d34ed6
      description: <p>the HTTP response </p>
- uid: com.microsoft.azure._cloud_exception.toString()
  id: toString()
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  langs:
  - java
  name: toString()
  fullName: String com.microsoft.azure.CloudException.toString()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-runtime/src/main/java/com/microsoft/azure/CloudException.java
    startLine: 96
  package: com.microsoft.azure
  syntax:
    content: public String toString()
    return:
      type: "26831127"
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: fa00b19f
  spec.java:
  - name: final Throwable
    fullName: final Throwable
- uid: e9d34ed6
  spec.java:
  - name: Response
    fullName: Response
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.rest._rest_exception.RestException()
  parent: com.microsoft.rest._rest_exception
  href: com.microsoft.rest._rest_exception.yml
  name: RestException()
  fullName: com.microsoft.rest.RestException.RestException()
  type: Constructor
  summary: <p>Initializes a new instance of the AutoRestException class. </p>
  syntax:
    content: public RestException()
- uid: com.microsoft.rest._rest_exception.RestException(String)
  parent: com.microsoft.rest._rest_exception
  href: com.microsoft.rest._rest_exception.yml
  name: RestException(String message)
  fullName: com.microsoft.rest.RestException.RestException(String message)
  type: Constructor
  summary: >-
    <p>Initializes a new instance of the AutoRestException class.</p>

    <p></p>
  syntax:
    content: public RestException(String message)
    parameters:
    - id: message
      type: "26831127"
      description: <p>The exception message. </p>
- uid: com.microsoft.rest._rest_exception.RestException(Throwable)
  parent: com.microsoft.rest._rest_exception
  href: com.microsoft.rest._rest_exception.yml
  name: RestException(Throwable cause)
  fullName: com.microsoft.rest.RestException.RestException(Throwable cause)
  type: Constructor
  summary: >-
    <p>Initializes a new instance of the AutoRestException class.</p>

    <p></p>
  syntax:
    content: public RestException(Throwable cause)
    parameters:
    - id: cause
      type: a04fafd7
      description: <p>exception that caused this exception to occur </p>
- uid: com.microsoft.rest._rest_exception.RestException(String,Throwable)
  parent: com.microsoft.rest._rest_exception
  href: com.microsoft.rest._rest_exception.yml
  name: RestException(String message, Throwable cause)
  fullName: com.microsoft.rest.RestException.RestException(String message, Throwable cause)
  type: Constructor
  summary: >-
    <p>Initializes a new instance of the AutoRestException class.</p>

    <p></p>
  syntax:
    content: public RestException(String message, Throwable cause)
    parameters:
    - id: message
      type: "26831127"
      description: <p>the exception message </p>
    - id: cause
      type: a04fafd7
      description: <p>exception that caused this exception to occur </p>
- uid: com.microsoft.rest._rest_exception
  parent: com.microsoft.rest
  href: com.microsoft.rest._rest_exception.yml
  name: RestException
  fullName: com.microsoft.rest.RestException
  type: Class
  summary: <p>Exception thrown for an invalid response with custom error information. </p>
  syntax:
    content: public class RestException
- uid: com.microsoft.azure.management.datalake.store.uploader._intentional_exception
  parent: com.microsoft.azure.management.datalake.store.uploader
  href: com.microsoft.azure.management.datalake.store.uploader._intentional_exception.yml
  name: IntentionalException
  fullName: com.microsoft.azure.management.datalake.store.uploader.IntentionalException
  type: Class
  summary: <p>An exception that we want our mocks to throw sometimes to test out various code paths. </p>
  syntax:
    content: public class IntentionalException
- uid: com.microsoft.azure._cloud_error
  parent: com.microsoft.azure
  href: com.microsoft.azure._cloud_error.yml
  name: CloudError
  fullName: com.microsoft.azure.CloudError
  type: Class
  summary: <p>An instance of this class provides additional information about an http error response. </p>
  syntax:
    content: public class CloudError
