items:
- uid: com.microsoft.azure.management.datalake.store.uploader._intentional_exception
  id: _intentional_exception
  parent: com.microsoft.azure.management.datalake.store.uploader
  href: com.microsoft.azure.management.datalake.store.uploader._intentional_exception.yml
  langs:
  - java
  name: IntentionalException
  fullName: com.microsoft.azure.management.datalake.store.uploader.IntentionalException
  type: Class
  source:
    remote:
      path: azure-mgmt-datalake-store-uploader/src/test/java/com/microsoft/azure/management/datalake/store/uploader/IntentionalException.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-datalake-store-uploader/src/test/java/com/microsoft/azure/management/datalake/store/uploader/IntentionalException.java
    startLine: 12
  package: com.microsoft.azure.management.datalake.store.uploader
  summary: <p>An exception that we want our mocks to throw sometimes to test out various code paths. </p>
  syntax:
    content: public class IntentionalException extends CloudException
  inheritance:
  - java.lang.Object
  - Exception
  - com.microsoft.rest._rest_exception
  - com.microsoft.azure._cloud_exception
  inheritedMembers:
  - com.microsoft.azure._cloud_exception.CloudException()
  - com.microsoft.azure._cloud_exception.CloudException(final String)
  - com.microsoft.azure._cloud_exception.CloudException(final String,final Throwable)
  - com.microsoft.azure._cloud_exception.CloudException(final Throwable)
  - com.microsoft.azure._cloud_exception.getBody()
  - com.microsoft.azure._cloud_exception.getResponse()
  - com.microsoft.rest._rest_exception.RestException()
  - com.microsoft.rest._rest_exception.RestException(String)
  - com.microsoft.rest._rest_exception.RestException(Throwable)
  - com.microsoft.rest._rest_exception.RestException(String,Throwable)
  - com.microsoft.azure._cloud_exception.setBody(CloudError)
  - com.microsoft.azure._cloud_exception.setResponse(Response)
  - com.microsoft.azure._cloud_exception.toString()
references:
- uid: com.microsoft.azure._cloud_exception.CloudException()
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  name: CloudException()
  fullName: com.microsoft.azure.CloudException.CloudException()
  type: Constructor
  summary: <p>Initializes a new instance of the ServiceException class. </p>
  syntax:
    content: public CloudException()
- uid: com.microsoft.azure._cloud_exception.CloudException(final String)
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  name: CloudException(final String message)
  fullName: com.microsoft.azure.CloudException.CloudException(final String message)
  type: Constructor
  summary: >-
    <p>Initializes a new instance of the ServiceException class.</p>

    <p></p>
  syntax:
    content: public CloudException(final String message)
    parameters:
    - id: message
      type: 3d93591e
      description: <p>The exception message. </p>
- uid: com.microsoft.azure._cloud_exception.CloudException(final String,final Throwable)
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  name: CloudException(final String message, final Throwable cause)
  fullName: com.microsoft.azure.CloudException.CloudException(final String message, final Throwable cause)
  type: Constructor
  summary: >-
    <p>Initializes a new instance of the ServiceException class.</p>

    <p></p>
  syntax:
    content: public CloudException(final String message, final Throwable cause)
    parameters:
    - id: message
      type: 3d93591e
      description: <p>the exception message </p>
    - id: cause
      type: fa00b19f
      description: <p>exception that caused this exception to occur </p>
- uid: com.microsoft.azure._cloud_exception.CloudException(final Throwable)
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  name: CloudException(final Throwable cause)
  fullName: com.microsoft.azure.CloudException.CloudException(final Throwable cause)
  type: Constructor
  summary: >-
    <p>Initializes a new instance of the ServiceException class.</p>

    <p></p>
  syntax:
    content: public CloudException(final Throwable cause)
    parameters:
    - id: cause
      type: fa00b19f
      description: <p>exception that caused this exception to occur </p>
- uid: com.microsoft.azure._cloud_exception.getBody()
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  name: getBody()
  fullName: CloudError com.microsoft.azure.CloudException.getBody()
  type: Method
  summary: >-
    <p>Gets the HTTP response body.</p>

    <p></p>
  syntax:
    content: public CloudError getBody()
    return:
      type: com.microsoft.azure._cloud_error
      description: <p>the response body </p>
- uid: com.microsoft.azure._cloud_exception.getResponse()
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  name: getResponse()
  fullName: Response com.microsoft.azure.CloudException.getResponse()
  type: Method
  summary: >-
    <p>Gets information about the associated HTTP response.</p>

    <p></p>
  syntax:
    content: public Response getResponse()
    return:
      type: e9d34ed6
      description: <p>the HTTP response </p>
- uid: com.microsoft.rest._rest_exception.RestException()
  parent: com.microsoft.rest._rest_exception
  href: com.microsoft.rest._rest_exception.yml
  name: RestException()
  fullName: com.microsoft.rest.RestException.RestException()
  type: Constructor
  summary: <p>Initializes a new instance of the AutoRestException class. </p>
  syntax:
    content: public RestException()
- uid: com.microsoft.rest._rest_exception.RestException(String)
  parent: com.microsoft.rest._rest_exception
  href: com.microsoft.rest._rest_exception.yml
  name: RestException(String message)
  fullName: com.microsoft.rest.RestException.RestException(String message)
  type: Constructor
  summary: >-
    <p>Initializes a new instance of the AutoRestException class.</p>

    <p></p>
  syntax:
    content: public RestException(String message)
    parameters:
    - id: message
      type: "26831127"
      description: <p>The exception message. </p>
- uid: com.microsoft.rest._rest_exception.RestException(Throwable)
  parent: com.microsoft.rest._rest_exception
  href: com.microsoft.rest._rest_exception.yml
  name: RestException(Throwable cause)
  fullName: com.microsoft.rest.RestException.RestException(Throwable cause)
  type: Constructor
  summary: >-
    <p>Initializes a new instance of the AutoRestException class.</p>

    <p></p>
  syntax:
    content: public RestException(Throwable cause)
    parameters:
    - id: cause
      type: a04fafd7
      description: <p>exception that caused this exception to occur </p>
- uid: com.microsoft.rest._rest_exception.RestException(String,Throwable)
  parent: com.microsoft.rest._rest_exception
  href: com.microsoft.rest._rest_exception.yml
  name: RestException(String message, Throwable cause)
  fullName: com.microsoft.rest.RestException.RestException(String message, Throwable cause)
  type: Constructor
  summary: >-
    <p>Initializes a new instance of the AutoRestException class.</p>

    <p></p>
  syntax:
    content: public RestException(String message, Throwable cause)
    parameters:
    - id: message
      type: "26831127"
      description: <p>the exception message </p>
    - id: cause
      type: a04fafd7
      description: <p>exception that caused this exception to occur </p>
- uid: com.microsoft.azure._cloud_exception.setBody(CloudError)
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  name: setBody(CloudError body)
  fullName: void com.microsoft.azure.CloudException.setBody(CloudError body)
  type: Method
  summary: >-
    <p>Sets the HTTP response body.</p>

    <p></p>
  syntax:
    content: public void setBody(CloudError body)
    parameters:
    - id: body
      type: com.microsoft.azure._cloud_error
      description: <p>the response object </p>
- uid: com.microsoft.azure._cloud_exception.setResponse(Response)
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  name: setResponse(Response response)
  fullName: void com.microsoft.azure.CloudException.setResponse(Response response)
  type: Method
  summary: >-
    <p>Sets the HTTP response.</p>

    <p></p>
  syntax:
    content: public void setResponse(Response response)
    parameters:
    - id: response
      type: e9d34ed6
      description: <p>the HTTP response </p>
- uid: com.microsoft.azure._cloud_exception.toString()
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  name: toString()
  fullName: String com.microsoft.azure.CloudException.toString()
  type: Method
  syntax:
    content: public String toString()
    return:
      type: "26831127"
- uid: com.microsoft.azure._cloud_exception
  parent: com.microsoft.azure
  href: com.microsoft.azure._cloud_exception.yml
  name: CloudException
  fullName: com.microsoft.azure.CloudException
  type: Class
  summary: <p>Exception thrown for an invalid response with custom error information. </p>
  syntax:
    content: public class CloudException extends RestException
